#!/usr/bin/env bash

# path:       /usr/bin/repomenue_snapper
# author:     The-Repo-Club [wayne6324@gmail.com]
# github:     https://github.com/The-Repo-Club/repomenu-snapshots
# date:       2021-09-16 16:34:47.440579

mnt='/mnt/750GB/.snapshots'

## Script metadata
SCRIPTNAME=${0##*/}
VERSION="2021.09.19"
DESCRIPTION="A bach BTRFS Sanpshot wrapper"
AUTHOR="The-Repo-Club <wayne6324@gmail.com>"

## Set Colors (copied from makepkg)
ALL_OFF="\e[1;0m"
RED="\e[1;31m"
GREEN="\e[1;32m"
YELLOW="\e[1;33m"
BLUE="\e[1;34m"
PURPLE="\e[1:35m"
CYAN="\e[1:36m"

readonly ALL_OFF RED GREEN YELLOW BLUE PURPLE CYAN

getsettings() {
    TERMINAL=$(gsettings get org.therepoclub.repomenu.preferences terminal | sed s/\'//g)
}

asksetting() {
    commands=
    if command -v snaplist &> /dev/null; then
        commands+=":g Snaplist\n:r Snapremove\n"
    fi

    if command -v snaphome &> /dev/null; then
        commands+=":p Snaphome\n"
    fi

    if command -v snaproot &> /dev/null; then
        commands+=":r Snaproot\n"
    fi

    if command -v snapshot &> /dev/null; then
        commands+=":r שׂSnapshot\n"
    fi
    echo -e "$commands" | sed '/^$/d' | repomenu -c -l 10 -w -300 -i -h -1 -bw 4 -q "${1:-Select snap package...}"
}

cmd_snaplist() {
    pkexec snaplist "--menu" | repomenu -c -l 10 -w -300 -i -h -1 -bw 4 -q "${1:-Select snap package...}" -wm
}

LOOPSETTING="true"
while [ -n "$LOOPSETTING" ]; do
    CHOICE="$(asksetting)"
    [ -n "$CHOICE" ] || exit
    unset LOOPSETTING
    getsettings
    snap=$(echo $CHOICE | awk -F"Snap" '{print $2}')
    case "$CHOICE" in
        *list)
            cmd_snaplist
            ;;
        *remove)
            package=$(cmd_snaplist | awk '{print $2}')
            [ -n "$package" ] || exit
            pkexec btrfs subvolume delete $mnt/$package
            ;;
        *home)
            $TERMINAL --title snapper --class snapper,Snapper -e sudo snap$snap
            ;;
        *root)
            $TERMINAL --title snapper --class snapper,Snapper -e sudo snap$snap
            ;;
        *shot)
            $TERMINAL --title snapper --class snapper,Snapper -e sudo snap$snap
            ;;
        *)
            echo "Program terminated."
            exit 1
            ;;
    esac
done
