#!/usr/bin/env bash
cmd=$(basename $0)

## Set Colors (copied from makepkg)
ALL_OFF="\e[1;0m"
RED="\e[1;31m"
GREEN="\e[1;32m"
YELLOW="\e[1;33m"
BLUE="\e[1;34m"
PURPLE="\e[1:35m"
CYAN="\e[1:36m"

readonly ALL_OFF RED GREEN YELLOW BLUE PURPLE CYAN

runas=$(whoami)

if [ $runas != 'root' ]; then
    printf ${GREEN}"%s ${RED}command must be ran as root${ALL_OFF}\n" "$cmd"
    exit
fi


if ! command -v snaphome &> /dev/null; then
    printf ${RED}"snaphome could not be found${ALL_OFF}\n"
    exit
else
    printf ${GREEN}"running snaphome.${ALL_OFF}\n"
    snaphome
fi

if ! command -v snaproot &> /dev/null; then
    printf ${RED}"snaproot could not be found${ALL_OFF}\n"
    exit
else
    printf ${GREEN}"running snaproot.${ALL_OFF}\n"
    snaproot
fi

if ! command -v grub-mkconfig &> /dev/null; then
    printf ${RED}"grub-mkconfig could not be found${ALL_OFF}\n"
    exit
else
    printf ${GREEN}"running grub-mkconfig.${ALL_OFF}\n"
    grub-mkconfig -o /boot/grub/grub.cfg
fi

printf "\n"
read -rsn1 -p"Press any key to continue";echo
