#!/usr/bin/env bash
cmd=$(basename $0)

## Set Colors (copied from makepkg)
ALL_OFF="\e[1;0m"
RED="\e[1;31m"
GREEN="\e[1;32m"
YELLOW="\e[1;33m"
BLUE="\e[1;34m"
PURPLE="\e[1:35m"
CYAN="\e[1:36m"

readonly ALL_OFF RED GREEN YELLOW BLUE PURPLE CYAN

runas=$(whoami)
echo $cmd

if [ $runas != 'root' ]; then
    printf ${GREEN}"%s ${RED}command must be ran as root\n" "$cmd"
    exit
fi


if ! command -v snaphome &> /dev/null; then
    printf ${RED}"snaphome could not be found\n"
    exit
else
    # snaphome
    printf ${GREEN}"running snaphome.\n"
fi

if ! command -v snaproot &> /dev/null; then
    printf ${RED}"snaproot could not be found\n"
    exit
else
    # snaproot
    printf ${GREEN}"running snaproot.\n"
fi

read
